### ISSUE TITLE
Invalid CSRF Token. Please try again later.

### ISSUE THREAD

**Issue by cemilsahin** [Code-Break0/SecureAuthSystem#1]
It get error below when creating a new record.

**Invalid CSRF Token. Please try again later.**

**Comment by Code-Break0** [comment]
Please be more specific I have no idea what circumstances could have caused this because you provided no detail.

**Comment by cemilsahin** [comment]
I'm getting this error on the new record creation screen
<img width="1047" alt="Screen Shot 2021-08-22 at 11 38 13" src="https://user-images.githubusercontent.com/7126731/130348157-025b8e15-5c24-41b1-926d-3b2848ed3426.png">

**Comment by Code-Break0** [comment]
This is an error of your own implementation. Not the code itself. I will mark issues as closed. If you are looking for how to fix this issue please watch the videos on my YouTube channel. If you directly copy and pasted the code, try re-downloading it, perhaps you have a premature version.


<img width="718" alt="Screen Shot 2021-08-31 at 11 30 26 AM" src="https://user-images.githubusercontent.com/41364583/131556862-ff4435fe-1e4c-4a91-a497-cb7a38456cb0.png">
