### ISSUE TITLE
Issue with account registration 

### ISSUE THREAD

**Issue by n1ck-thompson** [Code-Break0/SecureAuthSystem#12]
When I click the link to verify email, I get a 404. I think it has something to do with the "VALIDATE_EMAIL_ENDPOINT" but i don't know what to put for it

**Comment by Code-Break0** [comment]
the `VALIDATE_EMAIL_ENDPOINT` should be the url to the `validateEmail.php` file. The example I used is `http://localhost/YouTube/SecureAccountSystem/validate` which points to the `validateEmail.php` file in my setup. If you look in `.htaccess` you can see that `/validate` redirects to this php file.

You setup will likely look different, for example you probably dont have it in subfolders `Youtube/SecureAccountSystem`. 

You will need to update this path to reflect your setup.
