### ISSUE TITLE
Page doesn't work

### ISSUE THREAD

**Issue by Eddippla** [Code-Break0/SecureAuthSystem#2]

**Comment by Eddippla** [comment]
![image](https://user-images.githubusercontent.com/60261412/131541622-a88671cf-07f5-41fe-905a-da9b9f6a99ef.png)
sorry for no description, accidentally clicked enter.
when i load the website on firefox on my pc it works, but when anyone else loads it using a different browser or similar, it doesnt work, (it works on my phone on firefox, but not on chrome on my phone or on my PC with chrome), does this only work with firefox?

**Comment by Code-Break0** [comment]
Just tested and it loaded fine in Chrome. There is no browser specific code however perhaps you have a severely outdated version. I am going to mark as closed unless you are able to find code causes this.
