### ISSUE TITLE
Errors [1, 2, 4 and 9]

### ISSUE THREAD

**Issue by AGCodingGuy** [Code-Break0/SecureAuthSystem#4]
Wonderful code and great explanations! I don't know if others are experiencing issues, but I've followed your video for the registration form exactly, and have hit a roadblock. First, I'm using PHPMYADMIN in CPANEL, PHP Version 7.4.26, and my database connection entered in config.php has no problem (i.e., connection is successful). The database is set up exactly as on your channel (except its remote, and not local):

![image](https://user-images.githubusercontent.com/19391575/143731033-8ea3f45c-60cb-4973-89be-532bdd4f9afa.png)

I'm getting errors in register.php for [1, 2, 4] (name, email, password). When I comment out error 1-5 checks, I get an error for [9] for "Invalid CSRF Token"

![image](https://user-images.githubusercontent.com/19391575/143731023-25158bfd-d3ae-4e64-ae0e-d130304030b7.png)

![image](https://user-images.githubusercontent.com/19391575/143731145-2d8db141-7f89-447f-9621-ab2375c34a2b.png)

![image](https://user-images.githubusercontent.com/19391575/143731833-e56e1f7a-79c4-425f-8150-72f3216b5aa3.png)
![image](https://user-images.githubusercontent.com/19391575/143731861-28365c32-d5d7-46b0-9b35-7435046ff5fe.png)
_____________________

![image](https://user-images.githubusercontent.com/19391575/143731884-e24ed7f6-dc0f-4f20-98de-c73e3fba4c90.png)

I haven't changed any of your code in register.php and maintained your file structure. I've disabled ad-blockers, tried different browsers (Chrome, Firefox, Edge) and my site is using https. I'm not sure what the issue is, I've uninstalled and reinstalled twice.  

I apologize if this is a "setup" issue, but I can't seem to figure this out. My server error logs are giving me no web server errors:
![image](https://user-images.githubusercontent.com/19391575/143775584-12c7204e-564b-44a0-bcdc-a3c65ca9883a.png)

**Comment by Code-Break0** [comment]
Hmmmmmm 500 errors are tricky because the server doesn't really know what's going on either. Do you have a .htaccess file? A lot of times these errors can be caused by a syntax error in that file or some other bad configuration in there. I'm a little confused because at first you say you are getting a response back from the file (errors [1, 2, 4, 9]) but then later say you are just getting error 500. What causes you to get 500 and what causes you to get an actual response? Thank you for the detailed report as well!

**Comment by AGCodingGuy** [comment]
My .htaccess file is exactly the same as yours. I've tried shared hosts on both Bluehost.com and hostgator.com with the same result (both PHP supported Linux servers).

![image](https://user-images.githubusercontent.com/19391575/143789623-8bcc5d76-4c15-4d4d-b203-b6f22c861380.png).

Don't ask me why, but as of last night, I no longer get the 1, 2, 4, 9 errors, just the status 500. I'm at a total loss because the error files on the server are blank.
