### ISSUE TITLE
I cannot make the email verification to work 

### ISSUE THREAD

**Issue by diogomit9** [Code-Break0/SecureAuthSystem#6]
can you show me an example of the STMP file  ? It keeps showing the message unable to send email verification

**Comment by marcel-kraatz** [comment]
Hey, just randomly stepped across here and i think you mean the "php/config.php" File. For a Google-account it should look like this.
```
// Email Credentials
define('SMTP_HOST', 'smtp.gmail.com');
define('SMTP_PORT', 465);
define('SMTP_USERNAME', 'SOMEUSER@gmail.com'); #The Email of the account
define('SMTP_PASSWORD', 'APP-PASSWORD'); #Make sure to use a app-password for that.
define('SMTP_FROM', 'NOREPLY@EMAIL.COM'); 
define('SMTP_FROM_NAME', 'SENDERNAME'); 
```

**Comment by Code-Break0** [comment]
@diogomit9 yeah please take a look at [config.php](/php/config.php) like @marcel-kraatz mentions
