### ISSUE TITLE
Register.php

### ISSUE THREAD

**Issue by niklasbaranski** [Code-Break0/SecureAuthSystem#7]
![image](https://user-images.githubusercontent.com/87082036/225601719-48a6fd51-0cc7-45eb-b831-57f8a256c7ce.png)

looks like that, got the newest version.

**Comment by Code-Break0** [comment]
@niklasbaranski You closed the issue? The initial css link worked for me but if it is not working for you I can make a change. Please let me know what the resolution was

**Comment by niklasbaranski** [comment]
@Code-Break0 Perhaps I was a little too hasty there ;). You definitely have to change something there. But as you know, PHP got many possibilities.
You have in your code one not matching quotation mark after you close the php tag again.

Your code:
```<link rel="stylesheet" href=<?php echo dirname($_SERVER['PHP_SELF']) . '/style.css'; ?>" />```

The easiest way will be to simply remove the quotation mark. I personally prefer when linking HTML and PHP code that the quotation marks from the HTML code fully enclose the PHP code. In my opinion this makes it easier to read and understand the code.

So this is my suggestion:
<link rel="stylesheet" href="<?php echo dirname($_SERVER['PHP_SELF'])?>/style.css" />

**Comment by Code-Break0** [comment]
Thanks @niklasbaranski! I fixed the missing quote and added it back in, really appreciate that you caught this and brought it to my attention :).

**Comment by Niklas2290** [comment]
Hey, sorry to bother you. Is it possible to send you a message through Discord? It would be kind to be able to talk to you.

Kind regards

**Comment by Code-Break0** [comment]
@niklasbaranski sorry I do not have a discord, feel free to shoot me an email though!

**Comment by Niklas2290** [comment]
sure if you share them with me ;)

**Comment by Code-Break0** [comment]
Yeah sorry its on the about section of my YouTube channel I believe but I forgot to type it out in my last comment sorry: `codebreak05@gmail.com`

**Comment by Niklas2290** [comment]
yea no worries, thank you. I just send you an email (:
