### ISSUE TITLE
SecureAuthSystem setup not working

### ISSUE THREAD

**Issue by Niklas2290** [Code-Break0/SecureAuthSystem#8]
Hello,
I kind of have a little issues setting up your loginscript. When I change the CSRF_TOKEN_SECRET `[define('CSRF_TOKEN_SECRET', '<change me to something random>');]` I get the error  `Invalid CSRF Token. Please try again later.` . If I leave the CSRF_TOKEN_SECRET as it is, then I get the error `Failed to send email. Please try again later.
An entry is created in the database under Requests and User.
My configuration of the STMP mailer looks like this:
// Email Credentials
	define('SMTP_HOST', 'smtp.gmail.com');
	define('SMTP_PORT', 465);
	define('SMTP_USERNAME', 'meinemail@gmail.com');
	define('SMTP_PASSWORD', 'mypassword');
	define('SMTP_FROM', 'meinemail@gmail.com');
	define('SMTP_FROM_NAME', 'name lastname');

**Comment by Code-Break0** [comment]
Hmmm these seem like 2 separate issues but it is hard to tell without being able to look at your whole setup. Not sure why changing the CSRF_TOKEN_SECRET would cause issues. Are you sure that you are using this same configuration across all of your files? Do you make sure that you are actually passing a CSRF token? Do you call `session_start()` before validating the token or creating it? 

If possible could you please attach files?

**Comment by Niklas2290** [comment]
hm okay, I didn't change anything in the other files, so they should be as I downloaded them. 
Why the problem occurs I do not know. I also tried to enable debugging, but that didn't give me any output. Which files should I send you?

**Comment by Code-Break0** [comment]
Interesting… do you maybe have a public git repo you should share with me? Or could you make one? I was not able to reproduce the problem on my end

**Comment by Niklas2290** [comment]
I have not actually changed anything in the files. I only adjusted the config and then I came across the problems

**Comment by Code-Break0** [comment]
Closing. Please follow up if you think this is an error.
