### ISSUE TITLE
The script works great, except if I attempt to move the db config settings outside the root for improved security

### ISSUE THREAD

**Issue by zhoolu** [Code-Break0/SecureAuthSystem#9]
I moved the defined db settings outside the root public_html, chmod the file 400 to make it accessible to the app and added a require_once to the php/config.php file. The login page loads, but the xhr fails to send. Any solution to this?
KR
Mark

**Comment by Code-Break0** [comment]
@zhoolu you cannot make an XHR request to a file that is not under public_html because your web server will not make that file available.
